#!/usr/bin/env bash

if [ ! -z "$TZ" ]; then
    echo ${TZ} > /etc/timezone
    ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
