#!/usr/bin/env bash

if [ -n "$TZ" ]; then
    echo "${TZ}" > /etc/timezone
    ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime
fi

if [[ -n "$WWWUSER" && "$(id -u sail)" -ne "$WWWUSER" ]]; then
    usermod -u "$WWWUSER" sail
fi

chmod -R ugo+rw /home/sail/.composer

if [ $# -gt 0 ];then
    exec gosu "$WWWUSER" "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
